### ISSUE TITLE
TypeError: Cannot read property 'modules' of undefined

### ISSUE THREAD

**Issue by tu4mo** [egoist/rollup-plugin-postcss#188]
I'm getting an error building my project on **Windows**, everything works fine on a Mac.

```
[!] (plugin postcss) TypeError: Cannot read property 'modules' of undefined
TypeError: Cannot read property 'modules' of undefined
    at getExtracted (C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:771:60)
    at C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:814:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:19:24)
    at _next (C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:41:9)
    at C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:48:7
    at new Promise (<anonymous>)
    at C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:37:12
    at Object.generateBundle (C:\sg\node_modules\rollup-plugin-postcss\dist\index.js:859:9)
    at Promise.resolve.then (C:\sg\node_modules\rollup\dist\rollup.js:15921:25)
```

**Comment by tu4mo** [comment]
Error goes away when I remove `preserveModules` from config.

**Comment by kirsanv43** [comment]
Problem reproduce only in windows

**Comment by tu4mo** [comment]
https://github.com/egoist/rollup-plugin-postcss/pull/190 probably would fix this.

**Comment by tu4mo** [comment]
@egoist Any chance you could take a look at this?

**Comment by jlkiri** [comment]
I get the same error on Windows. That PR should fix it.
