### ISSUE TITLE
Postcss throws an error with namedExports

### ISSUE THREAD

**Issue by MissedWarrior** [egoist/rollup-plugin-postcss#239]
tldr: if there is a classname ``.default`` in scss file and there is a ``namedExports`` function in rollup config then rollup throws an error

I have a scss file that looks like that
```css
.default {
  display: inline-block;
}
```
and a file that imports it as a css module
```javascript
import s from './button.module.scss';
```
Running ``rollup -c `` throws an error
```
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/ui/button/button.module.scss: (1:11)
[!] Error: Unexpected keyword 'default' (Note that you need plugins to import files that are not JavaScript)
src/ui/button/button.module.scss (1:11)
1: .default {
             ^
2:   display: inline-block;
3: }
Error: Unexpected keyword 'default' (Note that you need plugins to import files that are not JavaScript)
    at error (/home/rasul/PhpstormProjects/postcss-named-export-bug/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/rasul/PhpstormProjects/postcss-named-export-bug/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at tryParse (/home/rasul/PhpstormProjects/postcss-named-export-bug/node_modules/rollup/dist/shared/node-entry.js:9717:23)
    at Module.setSource (/home/rasul/PhpstormProjects/postcss-named-export-bug/node_modules/rollup/dist/shared/node-entry.js:10080:33)
    at /home/rasul/PhpstormProjects/postcss-named-export-bug/node_modules/rollup/dist/shared/node-entry.js:12366:20
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```
This error disappeares if ``namedExports`` function would be removed or classname would be renamed to, for example, ``.default1``
Reproducible repo https://github.com/MissedWarrior/postcss-named-export-bug

**Comment by Himself65** [comment]
it seems that you parse the javascript reserved words, I'm going to update the `reserved-words` package🤔

**Comment by MissedWarrior** [comment]
Thanks for the fast response!
