### ISSUE TITLE
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by mohamedfrindi** [egoist/rollup-plugin-postcss#404]
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
style.css (1:5)
1: body {
        ^
2:     background: red;
3: }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:158:30)
    at Module.error (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:12382:16)
    at Module.tryParse (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:12785:25)
    at Module.setSource (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:12688:24)
    at ModuleLoader.addModuleSource (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:22148:20)
    at async ModuleLoader.fetchModule (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:22201:9)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:22236:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (C:\Users\med\Desktop\tes\node_modules\rollup\dist\shared\rollup.js:22212:9)

**Comment by JunwuHuang** [comment]
this error seems not from rollup-plugin-postcss.

maybe you need @rollup/plugin-node-resolve to resolve file not js format.

**Comment by mohamedfrindi** [comment]
Thank you, the problem has been solved and the problem is really not from postcss

**Comment by ListeningRift** [comment]
@mohamedfrindi May I ask what the reason is for this? I have this problem too and I don't know how to solve it
