### ISSUE TITLE
[!] Error: Could not resolve './AddressAutocomplete.scss'

### ISSUE THREAD

**Issue by noknokcody** [egoist/rollup-plugin-postcss#413]
I'm building a react component library in typescript / scss but whenever I use ```rollup -c``` I get the following error message.

``` bash
> rollup -c

src/index.ts → dist/cjs/index.js, dist/esm/index.js...
created dist/cjs/index.js, dist/esm/index.js in 2.9s

dist/esm/types/index.d.ts → dist/index.d.ts...
[!] Error: Could not resolve './AddressAutocomplete.scss' from dist\esm\types\components\AddressAutocomplete\index.d.ts
Error: Could not resolve './AddressAutocomplete.scss' from dist\esm\types\components\AddressAutocomplete\index.d.ts
    at error (...\address-autocomplete\node_modules\rollup\dist\shared\rollup.js:159:30)
    at ModuleLoader.handleResolveId (...\address-autocomplete\node_modules\rollup\dist\shared\rollup.js:22390:24)
    at ...\address-autocomplete\node_modules\rollup\dist\shared\rollup.js:22353:26
 ```
 
 I'm sure the problem sits somewhere between my chair and keyboard but if someone could help me out here you'd be a huge lifesaver as I'm pretty new to rollup / postcss / typescript in general.
 
 tsconfig.json
 ``` json
 {
  "compilerOptions": {
    "target": "es2015",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "module": "ESNext",                                  /* Specify what module code is generated. */

    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    "strict": true,        
    "skipLibCheck": true,
    
    "jsx": "react", 
    "declaration": true,
    "declarationDir": "types",
    "sourceMap": true,
    "outDir": "dist",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "emitDeclarationOnly": true
  }
}
```
 
 rollup.config.js
 
 ``` js
 import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "@rollup/plugin-typescript";
import dts from "rollup-plugin-dts";
import postcss from 'rollup-plugin-postcss'

const packageJson = require("./package.json");

export default [
    {
        input: "src/index.ts",
        output: [
            {
                file: packageJson.main,
                format: "cjs",
                sourcemap: true,
            },
            {
                file: packageJson.module,
                format: "esm",
                sourcemap: true,
            },
        ],
        plugins: [
            resolve(),
            postcss({
                sourceMap: true,
                extract: true,
            }),
            commonjs(),
            typescript({ tsconfig: "./tsconfig.json" })
        ],
    },
    {
        input: "dist/esm/types/index.d.ts",
        output: [{ file: "dist/index.d.ts", format: "esm" }],
        plugins: [dts()],
    }
];
```

AddressAutocomplete.scss
``` js
import "./AddressAutocomplete.scss";
export { default } from "./AddressAutocomplete"
```

package.json
``` json
{
  "description": "Component library for Address Autocomplete in react",
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
  "files": [
    "dist"
  ],
  "types": "dist/index.d.ts",
  "scripts": {
    "rollup": "rollup -c"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^21.0.2",
    "@rollup/plugin-node-resolve": "^13.1.3",
    "@rollup/plugin-typescript": "^8.3.1",
    "@types/react": "^17.0.39",
    "node-sass": "^7.0.1",
    "postcss": "^8.4.7",
    "react": "^17.0.2",
    "rollup": "^2.68.0",
    "rollup-plugin-dts": "^4.1.0",
    "rollup-plugin-postcss": "^4.0.2",
    "rollup-plugin-scss": "^3.0.0",
    "typescript": "^4.5.5"
  }
}
```

**Comment by noknokcody** [comment]
Figured it out, I was missing ```external: [/\.s?css$/]``` after ```plugins: [dts()],``` in my rollup.config.js

**Comment by realanalyticsdev** [comment]
@noknokcody Thank you!!!
